### ISSUE TITLE
Request thicker scroll bar

### ISSUE THREAD

**Issue by ngoncom** [arvi/Agila-Theme#10]
Hi Arvi,

I see little problem with horizontal scroll bar when searching.

Because scroll bar too thin, so cursor often change to resize instead of scoll.

http://i483.photobucket.com/albums/rr200/ngoncom/2016-06-18_220242_zps5k3nxcxu.jpg

Thank so much!

**Comment by arvi** [comment]
Hello :smile:

I agree with you on that as I was having a hard time myself :grin:

With that said, I have included your request on recent update. Just in case you prefer thicker scrollbars than the new default width (from 3, to 4), I have added two new options for scrollbar

SCROLLBAR THINNESS (if not set, will default to width: 4)

```
"theme_agila_vertical_scrollbar_thickest": true,   //width: 6
"theme_agila_horizontal_scrollbar_thickest": true,

"theme_agila_vertical_scrollbar_thicker": true,   //width: 5
"theme_agila_horizontal_scrollbar_thicker": true,
```

I've also added new schemes to the Agila family and an option to camouflage workspace with scheme background. :grin:
