### ISSUE TITLE
Agila Theme for Pycharm 

### ISSUE THREAD

**Issue by tanvirraj** [arvi/Agila-Theme#12]
Hey , 
Thanks for Awesome work .
i used sublime and pycharm both 
how can i use Agila theme in pycharm

**Comment by arvi** [comment]
Hello, 

Thanks for the appreciation.

I haven't used Pycharm... I'm not a python developer. I suggest you download via github Agila Theme then use the color schemes in Pycharm.

This article might help.

http://stackoverflow.com/questions/27116290/making-pycharm-look-like-sublime-text

Cheers :)
