### ISSUE TITLE
Override UI font with config value

### ISSUE THREAD

**Issue by AndydeCleyre** [arvi/Agila-Theme#13]
Hi,

I've been using Spacegray for the UI theme, but this looks like a great replacement, thank you!

Is it possible to add a setting for the UI font, to override the default used by the theme?

**Comment by arvi** [comment]
Thanks for the appreciation.

Yes it's possible if you manually edit your preferred theme, for example, adding the code snippet below just after https://github.com/arvi/Agila-Theme/blob/master/Agila.sublime-theme#L1641 if you're using the default Agila theme.

https://gist.github.com/arvi/af18cbda263f35ba56dc34231c33ca50 _(then add your preferred font face as the value of `font.face`)_

The only disadvantage is when I update the themes, you would have to add it again. Sublime settings only accept true/false so we can't do it via Sublime config file.
