### ISSUE TITLE
Reduce left and top margins in sidebar

### ISSUE THREAD

**Issue by AndydeCleyre** [arvi/Agila-Theme#14]
Hi,

The sidebar features some wasted space along the left and top edges.

Here's a screenshot of Spacegray's sidebar:

![spacegray_sidebar](https://cloud.githubusercontent.com/assets/1787385/17381261/14092f6a-5999-11e6-98ca-1142d0caf8f0.png)

And here's a screenshot of Agila's, with both `sidebar_small` and `compact_sidebar` enabled:

![agila_sidebar](https://cloud.githubusercontent.com/assets/1787385/17381321/50254df8-5999-11e6-805a-8139f6a89943.png)

**Comment by arvi** [comment]
Hmmmm I never really liked the lack of top and left spacing of spacegray 😄  Maybe I'll take a look at it over the weekend, if you're really interested in it. Have a great day ahead!

**Comment by arvi** [comment]
Keeping this as-is. :smile:
