### ISSUE TITLE
Provide an extra compact sidebar padding

### ISSUE THREAD

**Issue by mattiagalati** [arvi/Agila-Theme#18]
Can you please provide an extra small sidebar padding?
At this time, I've edited the theme file, adding this directive:
`{
                "class": "sidebar_tree",
                "settings": ["theme_agila_sidebar_mini"],
                "row_padding": [20, 5]
            },`
But my customizations gone when the package manager update Agila Theme.

**Comment by arvi** [comment]
Hello @mattiagalati 

Have you tried the `"theme_agila_compact_sidebar": true,` option? :smile: 

If that is not what you prefer, then i'll add your option tonight after my day job :smile:  just let me know. 

Thanks have a great day!

**Comment by mattiagalati** [comment]
Hello @arvi,
I'm already aware of `"theme_agila_compact_sidebar"` option, and I've already use it, but afaik, it only affects the horizontal padding of each row in the sidebar tree. 
For projects with a lot of files, I believe that a xsmall vertical padding of 5 or 4 would be a good compromise between space and readability.
However, I think your theme is an amazing work. Thanks.

**Comment by arvi** [comment]
Hello @mattiagalati 

Thanks for the appreciation. :smile: I will add 

```
["theme_agila_sidebar_mini"], "row_padding": [20, 5]
```

 later maybe 5 hours from now ha! I'm also working on Agila Cobalt2 theme, which I think is another great addition to Agila since it's constantly updated by Wes Bos.

**Comment by mattiagalati** [comment]
Many thanks!
I'll also give a try on Agila Cobalt2 when it will became available. I think that a good theme is, as well as features, an essential element on evaluation of editors or IDE.
An editor rich of features that burns your eyes is, for me, useless: that said, your work is priceless.

**Comment by arvi** [comment]
Your request has been included in recent push. :smile: I agree, in my case, I'm only using default Agila, Dracula, Origin, and Classic... I just added Cobalt2 and Neon for those who have different preference than me. Might be my last scheme addition to Agila family for this year. 

:smile:
