### ISSUE TITLE
Please Remove File Extension Preferences

### ISSUE THREAD

**Issue by adis-io** [arvi/Agila-Theme#22]
> The files at https://github.com/arvi/Agila-Theme/tree/master/preferences/Ext/ mess with the standard extension mapping.
> 
> It would be preferable to instead add a readme entry teaching people to use the View > Syntax > Open all with current extension as… menu.

https://github.com/equinusocio/material-theme/issues/682

**Comment by alekseychaikovsky** [comment]
+1 please remove this, having same issue as in linked issue above

**Comment by arvi** [comment]
@adisos @alekseychaikovsky Will do tonight after work, just been busy this past month. Thanks 😄

**Comment by alekseychaikovsky** [comment]
@arvi no worries, thanks for your great work on this beautiful theme :)

**Comment by arvi** [comment]
@alekseychaikovsky Thanks for the appreciation :smile: 

Request added in latest commit.
https://github.com/arvi/Agila-Theme/blob/master/CHANGELOG.md

**Comment by adisos** [comment]
@arvi 👍
