### ISSUE TITLE
php syntax highlighting issue

### ISSUE THREAD

**Issue by misterlami** [arvi/Agila-Theme#26]
setting:
```
        "theme": "Agila Origin.sublime-theme",
        "color_scheme": "Packages/Agila Theme/Agila Origin Oceanic Next.tmTheme",
```

A semicolon is not necessary when using a function the way it is used below (i.e. embedding php in HTML as a one-liner).

![image](https://cloud.githubusercontent.com/assets/1946090/22807864/35e64124-eef7-11e6-9fb8-dd65e31a309d.png)

Above should look like below even when the semicolon is removed.

![image](https://cloud.githubusercontent.com/assets/1946090/22807889/5fe18d3a-eef7-11e6-9633-d47c093bb9ed.png)

**Comment by arvi** [comment]
@mrlami  I ported my themes from existing color schemes and update it when there is an update on their repo. Maybe you can raise this issue to them. :smile: haven't updated this theme for a long time. will do updates this month. have a great day. :smile:
