### ISSUE TITLE
Smaller/Compact sidebar

### ISSUE THREAD

**Issue by nandcello** [arvi/Agila-Theme#27]
Swtiched from Material theme to this theme. Only thing I'm missing is the compact/smaller sidebar. Current ST3 sidebar is huuge on my small laptop display.

**Comment by arvi** [comment]
@ninoM hello there, can you share a screenshot on what you expect it to look like. Thanks a lot.

Also, have you tried any of these options?

**SIDEBAR COMPACT TREE STRUCTURE - NO INDENTATION**
`"theme_agila_compact_sidebar": true,`

**SIDEBAR TREE SIZE (default: medium)**
```
"theme_agila_sidebar_mini": true,
"theme_agila_sidebar_xsmall": true,
"theme_agila_sidebar_small": true,
"theme_agila_sidebar_medium": true,
"theme_agila_sidebar_large": true,
```
