### ISSUE TITLE
Readme Screenshot Question

### ISSUE THREAD

**Issue by gardiner** [arvi/Agila-Theme#28]
Hi, sorry for using an issue to contact you, but I didn't find any other way.
The screenshots of the (great!) Agila Theme show an icon toolbar at the bottom of the sidebar containing typographic tools of some sort. What toolbar is this? How do I enable it?

Thanks for the great work! Best,
Ole.

**Comment by arvi** [comment]
Hello @gardiner sorry, I must have missed reading the github notif regarding your comment.
Anyways, the bottom tools will appear when you CMD+F(mac) / CTRL + F (windows) :smile:

Thanks for the appreciation. :smile:

**Comment by gardiner** [comment]
Lol, of course you are right, it's just the search toolbar. I use it daily and still I had no idea... Thanks anyway for replying. Keep up the great work!

Best,
Ole.
