### ISSUE TITLE
Icons not loading

### ISSUE THREAD

**Issue by schroef** [arvi/Agila-Theme#32]
I seem to have issues with the icons. Seem they are not loaded correct
<img width="594" alt="screen shot 2017-11-12 at 05 21 45" src="https://user-images.githubusercontent.com/6923008/32697566-98a7bef2-c73f-11e7-96b4-1fea43641bc5.png">

Agila is installed in the user folder but has the name "Agila-Theme-2.2.0". Do i need to change this to Agila Theme?

**Comment by schroef** [comment]
Yep that was the fix
<img width="807" alt="screen shot 2017-11-12 at 05 24 43" src="https://user-images.githubusercontent.com/6923008/32697575-e68615d8-c73f-11e7-8e89-542884904292.png">

Perhaps add this aswell to install instructions. User needs to rename the unzipped folder to Agila Theme, no revision number or dashes

**Comment by arvi** [comment]
Thanks @schroef for the tips. I will include it in my README update. :smile:
