### ISSUE TITLE
Color Palette 

### ISSUE THREAD

**Issue by ghost** [arvi/Agila-Theme#34]
I really love this theme
Please can you share the colour palette(specific hexcodes for the colours), so i can port this theme to iTerm2 on MacOS as well as Atom and Vim?

**Comment by arvi** [comment]
@anuragroy11 Thanks! It's in the source code :smile: Let me know once you have ported it I want to also try haha :smile: I want to make one for VSCode, but haven't made time for it yet. If you do, that'd be great as well! Cheeeers!

Look for *.sublime-theme e.g

- https://github.com/arvi/Agila-Theme/blob/master/Agila.sublime-theme
- https://github.com/arvi/Agila-Theme/blob/master/Agila%20Origin.sublime-theme
- https://github.com/arvi/Agila-Theme/blob/master/Agila%20Monokai.sublime-theme
- https://github.com/arvi/Agila-Theme/blob/master/Agila%20Dracula.sublime-theme
- https://github.com/arvi/Agila-Theme/blob/master/Agila%20Cobalt.sublime-theme
