### ISSUE TITLE
SUGGESTION - add ability to choose what symbol you want for folders on the sidebar

### ISSUE THREAD

**Issue by ForestedDev** [arvi/Agila-Theme#40]
currently you can have + and - symbols on your sidebar however there are some assets i do not see used. that i was wondering if you could add the option to use these as an alternative to the + and - symbols. the assets in question are [fold-open.png](https://github.com/arvi/Agila-Theme/blob/master/assets/fold-open%402x.png) and [fold-closed.png](https://github.com/arvi/Agila-Theme/blob/master/assets/fold-closed%402x.png). alos, if you add this could you also make it so you can choose their color?

**Comment by ForestedDev** [comment]
i have managed to do this for monokai, will be posting code in a repo soon, if you would like sidebar arrows, just go download that i will have more detailed instructions soon.

the setting to turn on arrows is `"theme_agila_sidebar_arrows": true,`
i will be adding this to other themes soon as well so if your favorite agila theme is not included, i can add it, if you have made custom ones, i can add those as well. just post an issue on the repo.

**Comment by ForestedDev** [comment]
@arvi i am willing to share the changes to you if you will add them, i will be creating a pull request.

**Comment by ForestedDev** [comment]
leaving this open so people who come here can see this if they want this feature

**Comment by arvi** [comment]
@Vortetty that's great! Sure, you can go ahead for a pull request for custom arrows options you made for all Agila themes. I'll review it and merge if I don't see any issue. Thanks a lot.

**Comment by ForestedDev** [comment]
@arvi i'm currently working on this, communication may be delayed as where i live in 9 hours ahead of where you live. if you would like to test it i am almost done with monokai, i found a better arrow icon so i am adding that to my current edit, if you would like to see what it looks like i will be adding instructions to manually install it.

**Comment by ForestedDev** [comment]
@arvi i have added instructions [here](https://github.com/Vortetty/js-hosting-/tree/master/agila) i will be optimizing the arrows, then i will add this to the rest of the themes. the theme file used in the manual preview is not what will be merged with full repo, it is designed to be put in the one plugins files until a full release of the arrows feature is made.
