### ISSUE TITLE
blend sidebar and tab bar backgrounds with that of coding space (feature request)

### ISSUE THREAD

**Issue by misterlami** [arvi/Agila-Theme#9]

**Comment by arvi** [comment]
@mrlami thanks, will include an option on next release this week 😄

**Comment by misterlami** [comment]
awesome...  big thanks!

**Comment by arvi** [comment]
Hello 😄 

I have included your request on recent Agila update. 
- overrides default theme sidebar, scrollbars and tab background based on theme scheme background
  `"theme_agila_camouflage": true,`
- overrides default theme sidebar and tab background only based on theme scheme background
  `"theme_agila_camouflage_semi": true,`

I've also added new schemes to the Agila family.  :grin:
